config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout'}

  get 'static_pages/home', as: :home

  get 'static_pages/help', as: :help

  get 'static_pages/about', as: :about


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # , :controllers => { :users => "users", :sessions => "sessions" }

  root 'static_pages#home'

  get 'process_owner/:id/customer_job/:id/confirm',
    to: 'customer_jobs#confirm',
    as: :process_owner_customer_job_confirm

  # Delphi

  resources :organizations do
    resources :users
    resources :people
  end


  ## Process Owners
  resources :process_owners do
    resources :people
    resources :users
    resources :customers
    resources :suppliers
    resources :customer_jobs
    resources :supplier_orders
    resources :workshops
  end


  resources :action_result_updates
  resources :customer_job_updates
  resources :customer_updates
  resources :metric_updates
  resources :pain_point_updates
  resources :process_owner_updates
  resources :supplier_updates
  resources :supplier_order_updates
  resources :toe_tag_updates
  resources :workshop_updates

  ## Customers
  resources :customers do
    resources :customer_jobs
    resources :contacts
    resources :users
  end
  resources :customer_jobs do
    resources :action_results
    resources :status_updates
    resources :customer_job_updates
  end
  ## Suppliers
  resources :suppliers do
    resources :supplier_orders
    resources :users
    resources :contacts
  end
  resources :supplier_orders do
    resources :action_results
    resources :status_updates
  end
  resources :people do
    resources :status_updates
    resources :pain_point_updates
    resources :metrics
  end
  resources :workshops do
    resources :workshop_updates
  end
  resources :workshops do
    resources :action_results
    resources :toe_tags
    resources :pain_points
  end
  resources :action_results do
    resources :toe_tags
    resources :pain_points
    resources :updates
    resources :measurements
  end
  resources :toe_tags do
    resources :status_updates
  end
  resources :pain_points do
    resources :pain_point_updates
  end
  resources :metrics do
    resources :measurements
  end

  # Main Object Navigation
  resources :status_updates
  resources :date_lookups
  resources :pain_point_updates
  resources :measurements
  resources :toe_tags
  resources :pain_points


  # AJAX
  get 'ajax/email_compose',
      to: 'ajax#email_compose',
      as: :ajax_email_compose
  get 'ajax/email_list',
      to: 'ajax#email_list',
      as: :ajax_email_list
  get 'ajax/email_opened',
      to: 'ajax#email_opened',
      as: :ajax_email_opened
  get 'ajax/email_reply',
      to: 'ajax#email_reply',
      as: :ajax_email_reply
  get 'ajax/demo_widget',
      to: 'ajax#demo_widget',
      as: :ajax_demo_widget
  get 'ajax/data_list.json',
      to: 'ajax#data_list',
      as: :ajax_data_list
  get 'ajax/notify_mail',
      to: 'ajax#notify_mail',
      as: :ajax_notify_mail
  get 'ajax/notify_notifications',
      to: 'ajax#notify_notifications',
      as: :ajax_notify_notifications
  get 'ajax/notify_tasks',
      to: 'ajax#notify_tasks',
      as: :ajax_notify_tasks

  # Misc methods
  get '/home/set_locale',
      to: 'home#set_locale',
      as: :home_set_locale

  # CK editor
  mount Ckeditor::Engine => '/ckeditor'
end

app/models/workshop.rb
class Workshop < ApplicationRecord

  belongs_to :date_lookup
  belongs_to :process_owner

  has_many :triagers, inverse_of: :workshop
  has_many :people, through: :triagers, inverse_of: :workshops

  has_many :action_results, inverse_of: :workshop

  has_many :toe_tags, inverse_of: :workshop

  has_many :workshop_updates, inverse_of: :workshop

  has_many :pain_points, through: :toe_tags, inverse_of: :workshop


end

app/controllers/workshops_controller.rb
class WorkshopsController < ApplicationController

  before_action :set_parent_from_url, only: [:index, :new, :show, :update, :destroy, :create]
  before_action :set_edit_parent_from_url, only: [:new,  :edit]
  before_action :initialize_resource, only: [:show, :update, :destroy, :edit]
  before_action :initialize_new_resource, only: [:new]
  before_action :create_new_resource, only: [:create]
  before_action :initialize_resource_collection, only: [:index]

  # GET /workshops
  # GET /workshops.json
  def index
  end

  # GET /workshops/1
  # GET /workshops/1.json
  def show
    @toe_tags = @resource.toe_tags.all
    @action_results = @resource.action_results.all
    @pain_points = @resource.pain_points.all
    @participants = @resource.people.all
  end

  # GET /workshops/new
  def new
  end

  # GET /workshops/1/edit
  def edit
  end

  # POST /workshops
  # POST /workshops.json
  def create
    respond_to do |format|
      if @resource.save
        format.html { redirect_to process_owner_path( @parent ), notice: 'Workshop was successfully created.' }
        format.json { render :show, status: :created, location: @resource }
      else
        format.html { render :new }
        format.json { render json: @resource.errors, status: :unprocessable_entity }
      end
    end

  end

  # PATCH/PUT /workshops/1
  # PATCH/PUT /workshops/1.json
  def update
    respond_to do |format|
      if @resource.update(workshop_params)
        format.html { redirect_to workshop_path( @resource ), notice: 'Workshop was successfully updated.' }
        format.json { render :show, status: :ok, location: @resource }
      else
        set_edit_parent_from_url()
        format.html { render :edit }
        format.json { render json: @resource.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workshops/1
  # DELETE /workshops/1.json
  def destroy
    @resource.destroy
    respond_to do |format|
      format.html { redirect_to workshops_url, notice: 'Workshop was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private

    def set_parent_from_url
      # We set a default parent to this orgnaziation on the ApplicationCOontroller
      # @parent = ProcessOwner.find( params[:process_owner_id] || params[:process_owner][:id] )
    end
    def set_edit_parent_from_url

      # @edit_parent = ProcessOwner.find( params[:process_owner_id] )
    end
    def initialize_resource
      @resource = Workshop.find( params[:id] )
    end
    def initialize_new_resource
      @resource = @parent.workshops.new
    end
    def initialize_resource_collection
      @resources = @parent.workshops.all
    end
    def create_new_resource
      @resource = @parent.workshops.new( workshop_params )
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def workshop_params
      params.require(:workshop).permit(
          :date_lookup_id,
          :date,
          :process_owner_id,
          :capability_goal,
          :process_name,
          :process_description,
          :left_boundary,
          :right_boundary,
          :active
      )
    end

    def process_owner_params
      params.require(:process_owner).permit(
          :id
      );
    end

end

app/helpers/workshops_helper.rb
module WorkshopsHelper
end

app/views/workshops/_form.html.erb
<!-- render workshops/_form.html -->
<div class="row">
  <div class="col">
    <%= form_with( model: [parent, resource], local: true, class: 'smart-form', html: { novalidate: 'novalidate' } ) do |form| %>
      <fieldset>

        <div class="hidden fields">
          <%= hidden_field( :process_owner, :id, value:@edit_parent.id ) %>
        </div>


        <div class="row">
          <div class="col-sm mr-sm-3">
          </div>
          <div class="col-sm">
            <%= delphi_date_field(form, {label: 'Workshop Date', icon: 'fa fa-calendar', name: :date, value: Date.today.strftime('%F')}) %>
          </div>
        </div>


        <div class="row">
          <div class="col-sm">
            <%= delphi_text_field( form, { label: 'Process Name', name: :process_name} ) %>
          </div>
        </div>
        <div class="row">
          <div class="col-sm mr-sm-3">
            <%= delphi_text_field( form, { label: 'Left Boundary', icon: 'fa fa-arrow-left', name: :left_boundary } ) %>
          </div>
          <div class="col-sm">
            <%= delphi_text_field( form, { label: 'Right Boundary', icon: 'fa fa-arrow-right', name: :right_boundary } ) %>
          </div>
        </div>
        <div class="row">
          <div class="col-sm">
            <%= delphi_text_area( form, { label: 'Process Description', name: :process_description } ) %>
          </div>
        </div>
        <div class="row">
          <div class="col-sm">
            <%= delphi_text_field( form, { label: 'Capability Goal', name: :capability_goal } ) %>
          </div>
        </div>

      </fieldset>

      <footer>
        <%= submit_button( form, {buttonType: 'primary', icon: 'glyphicon-save'}) %>
      </footer>

    <% end %>`
  </div>
</div>

app/views/workshops/_profile.html.erb
<!-- render workshops/profile.html -->
<div class="row">
  <div class="col-sm">
    <h1><%= resource.process_name %></h1>
  </div>
  <div class="col-sm">
      <%= resource.capability_goal %><br>
      <%= resource.left_boundary %>, <%= resource.right_boundary %><br>
      <%= resource.process_description %>
  </div>
</div>

app/views/workshops/_table.html.erb
<div class="row">
  <div class="col table-responsive">
    <table class="table table-bordered table-striped table-condensed table-hover smart-form has-tickbox data-table">
      <thead>
      <tr>
        <th colspan="3">
          <%= small_button( { label: 'New Workshop', path: new_workshop_path( parent ), class: 'right' } ) %>
        </th>
      </tr>
      </thead>
      <tbody>
      <% resources.each do |row| %>
        <tr>
          <td>
            <span>Goal: <%= row.capability_goal %></span>
            <span>Process Name: <%= row.process_name %></span>
            <span>Process Description: <%= row.process_description %></span>
            <span>Left Boundary: <%= row.left_boundary %></span>
            <span>Right Boundary: <%= row.right_boundary %></span>
            <span class="five-eigths">
                <span class="text">Facilitator: Paul Osborn</span>
                <span class="text">Host: Freda Birke</span>
                <span class="links">
                  <%= link_to 'View', workshop_path( row ), class: 'link' %>&nbsp;|&nbsp;
                  <%= link_to 'Edit', edit_workshop_path( row ), class: 'link' %>&nbsp;|&nbsp;
                  <%= link_to '<i class="glyphicon glyphicon-remove"></i>Delete'.html_safe, [row], method: :delete, data: { confirm: 'Are you sure?' }, class: 'txt-color-red' %>
                </span>
            </span>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/workshops/edit.html.erb
<!-- CONTENT: workshops/edit.html -->
<%= page_title title: 'Edit Workshop', form_for: @parent %>
  <%= render  'workshops/form', resource: @resource, parent: @parent %>
<%= page_footer() %>
  <%= back_button path: process_owner_path( @parent ), label: 'Back' %>
<%= page_end() %>

app/views/workshops/index.html.erb
<!-- CONTENT: workshps/index.html -->
<%= page_title title: 'Workshops Taken By ' + @parent.name %>
  <%= render  'workshops/table', resources: @resources, parent: @parent %>
<%= page_footer() %>
<%= page_end() %>

app/views/workshops/new.html.erb
<!-- CONTENT: workshops/new.html -->
<%= page_title( { title: 'New Workshop ', form_for: @resource } ) %>
  <%= render 'form', resource: @resource, parent: @parent, edit_parent: @edit_parent %>
<%= page_footer() %>
  <%= back_button( { path: process_owner_path( @parent ) }) %>
<%= page_end() %>

app/views/workshops/show.html.erb
<!-- CONTENT: workshops/show.html -->
<%= page_title title: 'Workshop Overview' %>
  <%= render 'profile', resource: @resource, parent: @parent %>
<%= section_title({title: 'Participants'}) %>
  <%= render 'people/table', resources: @participants, parent: @resource %>
<%= section_title({title: 'Toe Tags'}) %>
  <%= render 'toe_tags/table', resources: @toe_tags, parent: @resource %>
<%= section_title({title: 'Process Map'}) %>
  <%= render 'action_results/table', resources: @action_results, parent: @resource %>
<%= section_title({title: 'Points of Pain'}) %>
  <%= render 'pain_points/table', resources: @pain_points, parent: @resource %>
<%= section_title title: 'Status Updates'  %>
  <%= link_to 'New Update', new_workshop_update_path( @resource ), class: 'btn btn-primary' %>
  <%= render partial: 'status_updates/status_update', collection: @resource.workshop_updates.sort_by_date %>
<%= page_footer() %>
  <%= back_button title: 'All Workshops', path: process_owner_path( @parent ), class: "left" %>
  <%= edit_button path: edit_process_owner_workshop_path( @parent, @resource ), buttonType: 'primary', class: "right" %>
<%= page_end() %>