config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout'}

  get 'static_pages/home', as: :home

  get 'static_pages/help', as: :help

  get 'static_pages/about', as: :about


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # , :controllers => { :users => "users", :sessions => "sessions" }

  root 'static_pages#home'

  get 'process_owner/:id/customer_job/:id/confirm',
    to: 'customer_jobs#confirm',
    as: :process_owner_customer_job_confirm

  # Delphi

  resources :organizations do
    resources :users
    resources :people
  end


  ## Process Owners
  resources :process_owners do
    resources :people
    resources :users
    resources :customers
    resources :suppliers
    resources :customer_jobs
    resources :supplier_orders
    resources :workshops
  end


  resources :action_result_updates
  resources :customer_job_updates
  resources :customer_updates
  resources :metric_updates
  resources :pain_point_updates
  resources :process_owner_updates
  resources :supplier_updates
  resources :supplier_order_updates
  resources :toe_tag_updates
  resources :workshop_updates

  ## Customers
  resources :customers do
    resources :customer_jobs
    resources :contacts
    resources :users
  end
  resources :customer_jobs do
    resources :action_results
    resources :status_updates
    resources :customer_job_updates
  end
  ## Suppliers
  resources :suppliers do
    resources :supplier_orders
    resources :users
    resources :contacts
  end
  resources :supplier_orders do
    resources :action_results
    resources :status_updates
  end
  resources :people do
    resources :status_updates
    resources :pain_point_updates
    resources :metrics
  end
  resources :workshops do
    resources :workshop_updates
  end
  resources :workshops do
    resources :action_results
    resources :toe_tags
    resources :pain_points
  end
  resources :action_results do
    resources :toe_tags
    resources :pain_points
    resources :updates
    resources :measurements
  end
  resources :toe_tags do
    resources :status_updates
  end
  resources :pain_points do
    resources :pain_point_updates
  end
  resources :metrics do
    resources :measurements
  end

  # Main Object Navigation
  resources :status_updates
  resources :date_lookups
  resources :pain_point_updates
  resources :measurements
  resources :toe_tags
  resources :pain_points


  # AJAX
  get 'ajax/email_compose',
      to: 'ajax#email_compose',
      as: :ajax_email_compose
  get 'ajax/email_list',
      to: 'ajax#email_list',
      as: :ajax_email_list
  get 'ajax/email_opened',
      to: 'ajax#email_opened',
      as: :ajax_email_opened
  get 'ajax/email_reply',
      to: 'ajax#email_reply',
      as: :ajax_email_reply
  get 'ajax/demo_widget',
      to: 'ajax#demo_widget',
      as: :ajax_demo_widget
  get 'ajax/data_list.json',
      to: 'ajax#data_list',
      as: :ajax_data_list
  get 'ajax/notify_mail',
      to: 'ajax#notify_mail',
      as: :ajax_notify_mail
  get 'ajax/notify_notifications',
      to: 'ajax#notify_notifications',
      as: :ajax_notify_notifications
  get 'ajax/notify_tasks',
      to: 'ajax#notify_tasks',
      as: :ajax_notify_tasks

  # Misc methods
  get '/home/set_locale',
      to: 'home#set_locale',
      as: :home_set_locale

  # CK editor
  mount Ckeditor::Engine => '/ckeditor'
end

app/models/pain_point.rb
class PainPoint < ApplicationRecord

  belongs_to :toe_tag, inverse_of: :pain_points

  belongs_to :process_owner, inverse_of: :pain_points

  belongs_to :action_result, inverse_of: :pain_points

  has_many :pain_point_updates, inverse_of: :pain_point

  has_one :workshop, through: :toe_tag

end

app/controllers/pain_points_controller.rb
class PainPointsController < ApplicationController

  before_action :set_parent_from_url, only: [:index, :new, :show, :update, :destroy, :create]
  before_action :set_edit_parent_from_url, only: [:new,  :edit]
  before_action :initialize_resource, only: [:show, :update, :destroy, :edit]
  before_action :initialize_new_resource, only: [:new]
  before_action :create_new_resource, only: [:create]
  before_action :initialize_resource_collection, only: [:index]

  # GET /pain_points
  # GET /pain_points.json
  def index
  end

  # GET /pain_points/1
  # GET /pain_points/1.json
  def show
  end

  # GET /pain_points/new
  def new
  end

  # GET /pain_points/1/edit
  def edit
  end

  # POST /pain_points
  # POST /pain_points.json
  def create

    respond_to do |format|
      if @resource.save
        format.html { redirect_to action_result_path( @parent ), notice: 'Pain Point successfully created.' }
        format.json { render :show, status: :created, location: @resource }
      else
        format.html { render :new, notice: 'An error occured!'  }
        format.json { render json: @resource.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pain_points/1
  # PATCH/PUT /pain_points/1.json
  def update
    respond_to do |format|
      if @resource.update( pain_point_params )
        format.html { redirect_to @resource, notice: 'Pain Point successfully updated.' }
        format.json { render :show, status: :ok, location: @resource }
      else
        format.html { render :edit }
        format.json { render json: @resource.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pain_points/1
  # DELETE /pain_points/1.json
  def destroy
    @pain_point.destroy
    respond_to do |format|
      format.html { redirect_to pain_points_url, notice: 'Pain Point was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def set_parent_from_url
    @parent = ActionResult.find( params[:action_result_id] || params[:action_result][:id] )
  end
  def set_edit_parent_from_url
    @edit_parent = action_result.find( params[:action_result_id] )
  end
  def initialize_resource
    @resource = PainPoint.find( params[:id] )
  end
  def initialize_new_resource
    @resource = @parent.pain_points.new
  end
  def initialize_resource_collection
    @resources = @parent.pain_points.all.order
    @pain_points = @resources
  end
  def create_new_resource
    @resource = @parent.pain_points.new( pain_point_params )
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def pain_point_params
    params.require(:pain_point).permit(
        :symptom,
        :impact
    )
  end

end

app/helpers/pain_points_helper.rb
module PainPointsHelper
end

app/views/pain_points/_form.html.erb
<!-- render people/new.html -->
<div class="row">
  <div class="col-sm">
    <%= form_with( model: [ resource ] , local: true, class: 'smart-form', html: { novalidate: 'novalidate' } ) do |form| %>
      <fieldset>

        <div class="row">
          <div class="col-sm">
            <%= collection_select( :pain_point, :action_result_id, dropdown, :id, :name, {:prompt =>'Which Action Result Location?'} ) %>
          </div>
        </div>
        <div class="row">
          <div class="col-sm mr-sm-3">
            <%= delphi_text_field( form, { label: 'Job Name', name: :job_name} ) %>
          </div>
          <div class="col-sm">
            <%= delphi_text_field( form,{ label: 'Reference #', name: :symptom} ) %>
          </div>
        </div>
        <div class="row">
          <div class="col-sm">
            <%= delphi_text_area(form, { label: 'Job Description', name: :impact} ) %>
          </div>
        </div>
      </fieldset>

      <footer>
        <%= submit_button( form, { buttonType: 'primary', icon: 'glyphicon-save'}) %>
      </footer>

    <% end %>`
  </div>
</div>

app/views/pain_points/_pain_point.html.erb
    <div class="row list-group-item"
         data-toggle="collapse"
         href="#collapse_<%= pain_point.id %>"
         role="button"
         aria-expanded="false"
         aria-controls="collapse_<%= pain_point.id %>">
      <div class="col-sm">
        <span class="name"><%= pain_point.symptom %></span>
        <span class="reference"><%= pain_point.impact %></span>
      </div>
    </div>
    <div id="collapse_<%= pain_point.id %>" class="row collapse" class="list-group-item">
      <div class="col-sm">
        <div class="row">
          <div class="col-sm">
            <%= link_to 'New Update', new_pain_point_update_path( pain_point ), class: 'btn btn-primary' %>
            <%= link_to 'View', pain_point_path( pain_point ), class: 'link' %>&nbsp;|&nbsp;
            <%= link_to 'Edit', edit_pain_point_path(  pain_point ), class: 'link' %>&nbsp;|&nbsp;
            <%= link_to '<i class="glyphicon glyphicon-remove"></i>Delete'.html_safe, pain_point, method: :delete, data: { confirm: 'Are you sure?' }, class: 'txt-color-red' %>
            <div class="job_description">
              <%= pain_point.job_description %>
            </div>
          </div>
        </div>

        <% @status_updates = pain_point.pain_point_updates.sort_by_date %>
        <%= render partial: 'status_updates/status_update', collection: @status_updates %>

      </div>
    </div><!--End of CustomerJob <%= pain_point.id %> -->

app/views/pain_points/_profile.html.erb
<!-- render people/profile .html -->
<div class="row">
  <!-- LEFT column -->
  <div class="col-sm">
    <h1><%= resource.symptom %></h1>
    <span class="semi-bold"><%= resource.toe_tag_id %></span>
  </div>
</div>
<div class="row">
  <div class="col-sm">
    <p><%= resource.impact %></p>
  </div>
</div>

app/views/pain_points/_table.html.erb
<!-- render pain_points/table.html -->
<div class="row">
  <div class="col table-responsive">
    <table class="table table-bordered table-striped table-condensed table-hover smart-form has-tickbox data-table">
      <thead>
        <tr>
          <th>
            <span><%= small_button( { label: 'Enter a New Job', path: new_workshop_pain_point_path( parent ), class: 'right'} ) %></span>
          </th>
        </tr>
      </thead>
      <tbody>
      <% resources.each do |row| %>
        <tr>
          <td >
            <span class="name"><%= row.symptom %></span>
            <span class="reference"><%= row.impact %></span>
            <span class="links">
              <%= link_to 'View', pain_point_path( row ), class: 'link' %>&nbsp;|&nbsp;
              <%= link_to 'Edit', edit_pain_point_path(  row ), class: 'link' %>&nbsp;|&nbsp;
              <%= link_to '<i class="glyphicon glyphicon-remove"></i>Delete'.html_safe, row, method: :delete, data: { confirm: 'Are you sure?' }, class: 'txt-color-red' %>
            </span>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div> 

app/views/pain_points/edit.html.erb
<!-- CONTENT: people/edit -->
<%= page_title( { title: @pain_point.symptom, form_for: @pain_point } ) %>
  <%= render 'form', resource: @pain_point, dropdown: @dropdown %>
<%= page_footer() %>
  <%= back_button({ path: pain_point_path, label: 'Back' }) %>
<%= page_end() %>

app/views/pain_points/index.html.erb
<!-- CONTENT: pain_points/index.html -->
<%= page_title( { title: 'Pain Points' } ) %>
  <div class="list-group">
    <%= render @pain_points %>
  </div> <!--End of List Group -->
<%= page_footer %>
<%= page_end %>

app/views/pain_points/new.html.erb
<!-- CONTENT: pain_points/new,html -->
<%= page_title( { title: 'New Point of Pain', form_for: @pain_point } ) %>
  <%= render 'form', resource: @pain_point, dropdown: @dropdown %>
<%= page_footer() %>
  <%= back_button( { path: workshop_path( @parent ) }) %>
<%= page_end() %>

app/views/pain_points/show.html.erb
<!-- CONTENT: pain_points/show.html -->
<%= page_title() %>
  <%= render 'profile', resource: @resource %>
  <%= section_title title: 'Status Updates' %>
    <%= link_to 'New Update', new_pain_point_update_path( @resource ), class: 'btn btn-primary' %>
    <%= render partial: 'status_updates/status_update', collection: @resource.pain_point_updates.sort_by_date %>
<%= page_footer() %>
  <%= back_button( { path: pain_points_path, class: "left"  }) %>
  <%= edit_button( { path: edit_pain_point_path( @resource ), buttonType: 'primary', class: "right" } ) %>
<%= page_end() %>