config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout'}

  get 'static_pages/home', as: :home

  get 'static_pages/help', as: :help

  get 'static_pages/about', as: :about


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # , :controllers => { :users => "users", :sessions => "sessions" }

  root 'static_pages#home'

  get 'process_owner/:id/customer_job/:id/confirm',
    to: 'customer_jobs#confirm',
    as: :process_owner_customer_job_confirm

  # Delphi

  resources :organizations do
    resources :users
    resources :people
  end


  ## Process Owners
  resources :process_owners do
    resources :people
    resources :users
    resources :customers
    resources :suppliers
    resources :customer_jobs
    resources :supplier_orders
    resources :workshops
  end


  resources :action_result_updates
  resources :customer_job_updates
  resources :customer_updates
  resources :metric_updates
  resources :pain_point_updates
  resources :process_owner_updates
  resources :supplier_updates
  resources :supplier_order_updates
  resources :toe_tag_updates
  resources :workshop_updates

  ## Customers
  resources :customers do
    resources :customer_jobs
    resources :contacts
    resources :users
  end
  resources :customer_jobs do
    resources :action_results
    resources :status_updates
    resources :customer_job_updates
  end
  ## Suppliers
  resources :suppliers do
    resources :supplier_orders
    resources :users
    resources :contacts
  end
  resources :supplier_orders do
    resources :action_results
    resources :status_updates
  end
  resources :people do
    resources :status_updates
    resources :pain_point_updates
    resources :metrics
  end
  resources :workshops do
    resources :workshop_updates
  end
  resources :workshops do
    resources :action_results
    resources :toe_tags
    resources :pain_points
  end
  resources :action_results do
    resources :toe_tags
    resources :pain_points
    resources :updates
    resources :measurements
  end
  resources :toe_tags do
    resources :status_updates
  end
  resources :pain_points do
    resources :pain_point_updates
  end
  resources :metrics do
    resources :measurements
  end

  # Main Object Navigation
  resources :status_updates
  resources :date_lookups
  resources :pain_point_updates
  resources :measurements
  resources :toe_tags
  resources :pain_points


  # AJAX
  get 'ajax/email_compose',
      to: 'ajax#email_compose',
      as: :ajax_email_compose
  get 'ajax/email_list',
      to: 'ajax#email_list',
      as: :ajax_email_list
  get 'ajax/email_opened',
      to: 'ajax#email_opened',
      as: :ajax_email_opened
  get 'ajax/email_reply',
      to: 'ajax#email_reply',
      as: :ajax_email_reply
  get 'ajax/demo_widget',
      to: 'ajax#demo_widget',
      as: :ajax_demo_widget
  get 'ajax/data_list.json',
      to: 'ajax#data_list',
      as: :ajax_data_list
  get 'ajax/notify_mail',
      to: 'ajax#notify_mail',
      as: :ajax_notify_mail
  get 'ajax/notify_notifications',
      to: 'ajax#notify_notifications',
      as: :ajax_notify_notifications
  get 'ajax/notify_tasks',
      to: 'ajax#notify_tasks',
      as: :ajax_notify_tasks

  # Misc methods
  get '/home/set_locale',
      to: 'home#set_locale',
      as: :home_set_locale

  # CK editor
  mount Ckeditor::Engine => '/ckeditor'
end

app/models/date_lookup.rb
class DateLookup < ApplicationRecord

  has_many :workshops, inverse_of: :date_lookup
 #   delegate  :date, to: :workshops, prefix: false
  has_many :status_updates, inverse_of: :date_lookup
  #  delegate :date, to: :status_updates, prefix: false

end

app/controllers/date_lookups_controller.rb
class DateLookupsController < ApplicationController

  before_action :set_date_lookup, only: [:show, :edit, :update, :destroy]

  # GET /date_lookups
  # GET /date_lookups.json
  def index
    @date_lookups = DateLookup.all
  end

  # GET /date_lookups/1
  # GET /date_lookups/1.json
  def show
  end

  # GET /date_lookups/new
  def new
    @date_lookup = DateLookup.new
  end

  # GET /date_lookups/1/edit
  def edit
  end

  # POST /date_lookups
  # POST /date_lookups.json
  def create
    @date_lookup = DateLookup.new(date_lookup_params)

    respond_to do |format|
      if @date_lookup.save
        format.html { redirect_to @date_lookup, notice: 'Date lookup was successfully created.' }
        format.json { render :show, status: :created, location: @date_lookup }
      else
        format.html { render :new }
        format.json { render json: @date_lookup.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /date_lookups/1
  # PATCH/PUT /date_lookups/1.json
  def update
    respond_to do |format|
      if @date_lookup.update(date_lookup_params)
        format.html { redirect_to @date_lookup, notice: 'Date lookup was successfully updated.' }
        format.json { render :show, status: :ok, location: @date_lookup }
      else
        format.html { render :edit }
        format.json { render json: @date_lookup.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /date_lookups/1
  # DELETE /date_lookups/1.json
  def destroy
    @date_lookup.destroy
    respond_to do |format|
      format.html { redirect_to date_lookups_url, notice: 'Date lookup was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_date_lookup
      @date_lookup = DateLookup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def date_lookup_params
      params.require(:date_lookup).permit(:date, :day_of_month, :month, :quarter, :year, :week_of_year, :week_of_quarter)
    end
end

app/helpers/date_lookups_helper.rb
module DateLookupsHelper
end

app/views/date_lookups/_form.html.erb
<%= form_with(model: date_lookup, local: true) do |form| %>
  <% if date_lookup.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(date_lookup.errors.count, "error") %> prohibited this date_lookup from being saved:</h2>

      <ul>
      <% date_lookup.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date, id: :date_lookup_date %>
  </div>

  <div class="field">
    <%= form.label :day_of_month %>
    <%= form.number_field :day_of_month, id: :date_lookup_day_of_month %>
  </div>

  <div class="field">
    <%= form.label :month %>
    <%= form.number_field :month, id: :date_lookup_month %>
  </div>

  <div class="field">
    <%= form.label :quarter %>
    <%= form.number_field :quarter, id: :date_lookup_quarter %>
  </div>

  <div class="field">
    <%= form.label :year %>
    <%= form.number_field :year, id: :date_lookup_year %>
  </div>

  <div class="field">
    <%= form.label :week_of_year %>
    <%= form.number_field :week_of_year, id: :date_lookup_week_of_year %>
  </div>

  <div class="field">
    <%= form.label :week_of_quarter %>
    <%= form.number_field :week_of_quarter, id: :date_lookup_week_of_quarter %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/date_lookups/edit.html.erb
<h1>Editing Date Lookup</h1>

<%= render 'form', date_lookup: @date_lookup %>

<%= link_to 'Show', @date_lookup %> |
<%= link_to 'Back', date_lookups_path %>

app/views/date_lookups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Date Lookups</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Day of month</th>
      <th>Month</th>
      <th>Quarter</th>
      <th>Year</th>
      <th>Week of year</th>
      <th>Week of quarter</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @date_lookups.each do |date_lookup| %>
      <tr>
        <td><%= date_lookup.date %></td>
        <td><%= date_lookup.day_of_month %></td>
        <td><%= date_lookup.month %></td>
        <td><%= date_lookup.quarter %></td>
        <td><%= date_lookup.year %></td>
        <td><%= date_lookup.week_of_year %></td>
        <td><%= date_lookup.week_of_quarter %></td>
        <td><%= link_to 'Show', date_lookup %></td>
        <td><%= link_to 'Edit', edit_date_lookup_path(date_lookup) %></td>
        <td><%= link_to 'Destroy', date_lookup, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Date Lookup', new_date_lookup_path %>

app/views/date_lookups/new.html.erb
<h1>New Date Lookup</h1>

<%= render 'form', date_lookup: @date_lookup %>

<%= link_to 'Back', date_lookups_path %>

app/views/date_lookups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @date_lookup.date %>
</p>

<p>
  <strong>Day of month:</strong>
  <%= @date_lookup.day_of_month %>
</p>

<p>
  <strong>Month:</strong>
  <%= @date_lookup.month %>
</p>

<p>
  <strong>Quarter:</strong>
  <%= @date_lookup.quarter %>
</p>

<p>
  <strong>Year:</strong>
  <%= @date_lookup.year %>
</p>

<p>
  <strong>Week of year:</strong>
  <%= @date_lookup.week_of_year %>
</p>

<p>
  <strong>Week of quarter:</strong>
  <%= @date_lookup.week_of_quarter %>
</p>

<%= link_to 'Edit', edit_date_lookup_path(@date_lookup) %> |
<%= link_to 'Back', date_lookups_path %>